### PR TITLE
Adding a CLI

### PR DESCRIPTION
**Pull request by dominicbarnes**
While working on a revamped simulator, I've decide it's best to create docker containers for each library. In addition, it's way easier `docker run` things that have a CLI, so I've added one here. It also turned out this tool could be useful for success engineers or for debugging, so I've created this as a separate PR after discussing with @calvinfo.

The big idea is that you add a `$SEGMENT_WRITE_KEY` to your env and then you can run the following commands:

```bash
$ analytics track <event> [options]
$ analytics identify [options]
$ analytics group [options]
$ analytics alias [options]
$ analytics page [options]
```

All the options are consistent throughout the commands, which you can see by using `--help`.

**NOTE:** This adds 1 more dependency to `analytics-node` itself, which is [commander](https://www.npmjs.com/package/commander). (it's a lightweight) This does not inflate the browserify build at all. (since it's only being used in the `bin/` dir)

### CODE REVIEW

**Comment by stephenmathieson** [comment]
should we support `--write-key=ABCDEFG`?

**Comment by stephenmathieson** [comment]
i think it'd be cool to use commander's `.command()`s.  this would let us remove a bunch of the copypasta in `./bin/*` too

**Comment by dominicbarnes** [comment]
@stephenmathieson both suggestions have been applied :)

**Comment by stevenmiller888** [comment]
This is cool. Still planning to merge?

**Pull request merged**
