### PR TITLE
Fix: @angular/cli@1.4.5 Error by adding json file extension

### LINKED ISSUE #122: Integrating into Angular CLI v1.4.5
Seems that the Angular CLI only accepts dropping the file extensions `.ts` and `.js`

The line that causes the build issue is [here](https://github.com/segmentio/analytics-node/blob/4290503572a7c9661661dbcafef75b573cdbda0b/index.js#L9).

A simple fix would be to change this `const version = require('./package').version` to this `const version = require('./package.json').version`.

I know this is outside the scope of this library but thought you all may want to offer Angular CLI support as well :)

### Console Error
```
ERROR in ./node_modules/analytics-node/index.js
Module not found: Error: Can't resolve './package' in '/.../node_modules/analytics-node'
resolve './package' in '/.../node_modules/analytics-node'
  using description file: /.../node_modules/analytics-node/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /.../node_modules/analytics-node/package.json (relative path: .)
    using description file: /.../node_modules/analytics-node/package.json (relative path: ./package)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /.../node_modules/analytics-node/package doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /.../node_modules/analytics-node/package.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /.../node_modules/analytics-node/package.js doesn't exist
      as directory
        /.../node_modules/analytics-node/package doesn't exist
[/.../node_modules/analytics-node/package]
[/.../node_modules/analytics-node/package.ts]
[/.../node_modules/analytics-node/package.js]
[/.../node_modules/analytics-node/package]
 @ ./node_modules/analytics-node/index.js 9:16-36
 @ ./src/app/store/effects/user.effects.ts
 @ ./src/app/store/effects/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

webpack: Failed to compile.
```

### PR DESCRIPTION
**Pull request by timdoes**
Fixes #122

### CODE REVIEW

**Comment by vadimdemedes** [comment]
That seems more like an error that belongs to `@angular/cli`, because Node.js natively supports `require()`ing JSON files, without an explicit extension. Did you try searching for existing issues there or opening a new one?

**Comment by timdoes** [comment]
I will create an issue over there tomorrow. I also think it’s more of a TypeScript error due to their tsconfig only allowing ‘.js’ and ‘.ts’ extensions to be dropped.

I agree it should be opened up on their end to us users. Just thought adding the explicit extension would be harmless and a quick fix for all. Thank you for getting back to me as well :)

**Comment by vadimdemedes** [comment]
No worries! I just think it's something that `@angular/cli` is missing and will be a benefit for them to have. You wouldn't want to create PRs for all dependencies that don't use a `.json` extension after all, right? 😆

**Comment by stephenmathieson** [comment]
While I agree, this is 100% an issue on the Angular side, if we can resolve @timdoes's issue by adding a file extension to a require (5 chars), I think it's worth it.

I'm going to look into why the tests are failing and will merge this soon.

**Comment by timdoes** [comment]
Looks like there is a [superagent Large gzip Denial of Service error](https://nodesecurity.io/advisories/479)

**Comment by stephenmathieson** [comment]
@timdoes yep! I saw that too. We've been wanting an excuse to get rid of superagent for a long time now, and this a great one!

See #124 and #126.

I'll merge this right after we get rid of superagent.

**Comment by stephenmathieson** [comment]
Thanks Tim!

**Pull request merged**
